### ISSUE TITLE
r-build-check fail

### ISSUE THREAD

**Issue by atuldeshpande** [atuldeshpande/SpaceMarkers#19]
@dimalvovs I see r-build-check failing for all 3 OS's. It may be likely due to R version mismatch between DESCRIPTION and the r-build-check script.

**Comment by dimalvovs** [comment]
@atuldeshpande thanks for migrating to the lab's version, its much easier to support all in one place. it's not a problem to add 'devel' vesion of R to workers, do you think we should increase the default number of runs to 6 then (mac, unix, win on release and on devel)?

**Comment by atuldeshpande** [comment]
I think the devel check could be run only if the default fails, perhaps?

**Comment by dimalvovs** [comment]
there has been interest to start building `devel` by other projects, so I created the version v1.2.2 to build both and it passed the[ mock build](https://github.com/FertigLab/actions/actions/runs/7921902247/job/21628252480), feel free to use!
